# Dockerfile for frontend
FROM node:20-alpine

# Set the working directory to /app
WORKDIR /frontend

# Copy the current directory contents into the container at /app
COPY . .

RUN npm i --silent

# Expose the port that the app will run on
EXPOSE 3000

# Define the command to run your application
CMD ["npm", "run", "dev"]