apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: backend-container
        image: iwinterr/jkpgcity:backend # Replace with the actual image name
        ports:
        - containerPort: 3001
        env:
        - name: CHOKIDAR_USEPOLLING
          value: "true"
        resources:
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001