version: '3.9'
services:  #Describes the containers that make up the application
  backend:
    container_name: backend-container
    build: ./backend/    # Build from the root of the project
    environment:         #Defines environment variables for the container
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3001:3001"
    volumes:  #Mounts the local "./backend/src/" directory into the "/backend/src/" directory in the container
      - ./backend/src:/backend/src/
    networks:
      - jkpgcity_network
    

  frontend:
    container_name: frontend-container
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/frontend/src/
    networks:
      - jkpgcity_network

networks:
  jkpgcity_network:
    driver: bridge