version: '3.9'
services:
  backend:
    container_name: backend-container
    build: ./backend/
    environment:
      CHOKIDAR_USEPOLLING: true
    ports:
      - '3001:3001'
    volumes:
      - ./backend/src:/backend/src/
    networks:
      - jkpgcity_network

  frontend:
    container_name: frontend-container
    build: ./frontend/
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/frontend/src/
    networks:
      - jkpgcity_network

  mongodb:
    image: mongo
    environment:
      - MONGO_URI=mongodb+srv://wajd:admin2024@jkpcity.sktnmlb.mongodb.net/
    ports:
      - '8081:8081'
    networks:
      - jkpgcity_network

networks:
  jkpgcity_network:
    driver: bridge
